event_listeners:
    base_route:
        class: "Evan\Routing\EventListeners\RouteListener"
        arguments:
            "@app"
        subscribe:
            addRouteBefore: addRouteBefore
            addRouteAfter: addRouteAfter
            routeNotFound: routeNotFound
# Listener in charge of EmptyControllerClass submitted to ControllerFactory
    empty_controller_manipulator:
        class: "Evan\Controller\EventListeners\DefaultControllerListener"
        arguments:
            "@app"
        subscribe:
            newControllerInstanceBefore: newControllerInstanceBefore