routing:
    evan_base_route:
        route: /
        controller: "Evan\Controller\BaseController"
        action: "index"
        methods: "GET|POST"
        options:
            expose: true
    evan_test_route:
        route: /test/{toto}
        controller: plop
        action: "index"
        methods: "GET|POST"
        options:
            expose: false