#!/usr/bin/env php
<?php

use Doctrine\ORM\Tools\Console\ConsoleRunner;

require_once 'Kernel.php';

// replace with mechanism to retrieve EntityManager in your app
$entityManager = $app['entityManager'];

$helperSet = new Symfony\Component\Console\Helper\HelperSet(array(
    'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($entityManager->getConnection()),
    'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper($entityManager)
));

return ConsoleRunner::run($helperSet);